-- MySQL Script generated by MySQL Workbench
-- Wed Dec 20 23:00:32 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`File`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`File` ;

CREATE TABLE IF NOT EXISTS `mydb`.`File` (
  `file_id` INT NOT NULL AUTO_INCREMENT,
  `file_path` VARCHAR(100) NULL,
  `post_id` INT NOT NULL,
  `member_id` INT NOT NULL,
  PRIMARY KEY (`file_id`),
  UNIQUE INDEX `file_id_UNIQUE` (`file_id` ASC) VISIBLE,
  CONSTRAINT `file_connect_post`
    FOREIGN KEY (`post_id`)
    REFERENCES `mydb`.`Post` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`File`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`File` (`file_id`, `file_path`, `post_id`, `member_id`) VALUES (1, '112_SA_project_G2/filepath/sanote1_1.png', 1, 1);
INSERT INTO `mydb`.`File` (`file_id`, `file_path`, `post_id`, `member_id`) VALUES (2, '112_SA_project_G2/filepath/algorithm2_1.pdf', 2, 1);
INSERT INTO `mydb`.`File` (`file_id`, `file_path`, `post_id`, `member_id`) VALUES (3, NULL, 3, 1);
INSERT INTO `mydb`.`File` (`file_id`, `file_path`, `post_id`, `member_id`) VALUES (4, NULL, 6, 2);
INSERT INTO `mydb`.`File` (`file_id`, `file_path`, `post_id`, `member_id`) VALUES (5, '112_SA_project_G2/filepath/accounting2_1.png', 7, 2);
INSERT INTO `mydb`.`File` (`file_id`, `file_path`, `post_id`, `member_id`) VALUES (6, NULL, 8, 2);
INSERT INTO `mydb`.`File` (`file_id`, `file_path`, `post_id`, `member_id`) VALUES (7, NULL, 9, 2);
INSERT INTO `mydb`.`File` (`file_id`, `file_path`, `post_id`, `member_id`) VALUES (8, NULL, 11, 2);
INSERT INTO `mydb`.`File` (`file_id`, `file_path`, `post_id`, `member_id`) VALUES (9, NULL, 12, 3);
INSERT INTO `mydb`.`File` (`file_id`, `file_path`, `post_id`, `member_id`) VALUES (10, '112_SA_project_G2/filepath/linear_algebra3_1.pptx', 13, 3);
INSERT INTO `mydb`.`File` (`file_id`, `file_path`, `post_id`, `member_id`) VALUES (11, '112_SA_project_G2/filepath/sanote1_2.png', 1, 1);
INSERT INTO `mydb`.`File` (`file_id`, `file_path`, `post_id`, `member_id`) VALUES (12, '112_SA_project_G2/filepath/sanote1_3.png', 1, 1);
INSERT INTO `mydb`.`File` (`file_id`, `file_path`, `post_id`, `member_id`) VALUES (DEFAULT, '112_SA_project_G2/filepath/accounting2_2.png', 7, 2);
INSERT INTO `mydb`.`File` (`file_id`, `file_path`, `post_id`, `member_id`) VALUES (DEFAULT, '112_SA_project_G2/filepath/accounting2_3.png', 7, 2);

COMMIT;

