-- MySQL Script generated by MySQL Workbench
-- Wed Dec 20 23:01:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Keyword`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Keyword` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Keyword` (
  `keyword_id` INT NOT NULL AUTO_INCREMENT,
  `word` VARCHAR(60) NULL,
  `post_id` INT NOT NULL,
  PRIMARY KEY (`keyword_id`),
  UNIQUE INDEX `keyword_id_UNIQUE` (`keyword_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Keyword`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (1, 'sa', 1);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (2, 'Sa', 1);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (3, 'SA', 1);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (4, 'system analysis', 1);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (5, 'System Analysis', 1);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (6, 'note', 1);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (7, 'notebook', 1);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (8, 'class note', 1);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (9, 'course note', 1);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (10, 'course', 1);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (11, 'information management', 1);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (12, 'im', 1);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (13, 'IM', 1);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (14, 'algorithm', 2);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (15, 'cs', 2);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (16, 'CS', 2);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (17, 'computer science', 2);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (18, 'note', 2);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (19, 'note book', 2);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (20, 'course note', 2);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (21, 'finance', 3);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (22, 'material', 3);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (23, 'course material', 3);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (24, 'Finance', 3);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (25, 'invest', 3);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (26, 'investment', 3);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (27, 'english', 4);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (29, 'English', 4);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (30, 'En', 4);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (31, 'en', 4);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (32, 'feedback', 4);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (33, 'Feedback', 4);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (34, 'course feedback', 4);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (35, 'english course', 4);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (36, 'chinese', 5);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (37, 'Chinese', 5);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (38, 'chinese course', 5);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (39, 'feedback', 5);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (40, 'Feedback', 5);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (41, 'math', 6);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (42, 'Math', 6);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (43, 'Intermediate', 6);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (44, 'intermediate', 6);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (45, 'note', 6);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (46, 'Note', 6);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (47, 'note book', 6);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (48, 'class note', 6);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (49, 'course note', 6);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (50, 'accounting', 7);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (51, 'Accounting', 7);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (52, 'course', 7);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (53, 'course note', 7);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (54, 'note', 7);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (55, 'note book', 7);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (56, 'linear', 8);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (57, 'Linear', 8);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (58, 'algebra', 8);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (59, 'Algebra', 8);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (60, 'linear algebra', 8);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (61, 'course material', 8);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (62, 'material', 8);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (63, 'course', 8);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (64, 'phsics', 9);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (65, 'phsic', 9);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (66, 'foundation', 9);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (67, 'foundational', 9);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (68, 'course', 9);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (69, 'book', 9);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (70, 'text book', 9);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (71, 'material', 9);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (72, 'class material', 9);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (73, 'course material', 9);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (74, 'sa', 10);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (75, 'SA', 10);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (76, 'Sa', 10);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (77, 'system analysis', 10);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (78, 'feedback', 10);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (79, 'course feedback', 10);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (80, 'chemistry', 11);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (81, 'Chemistry', 11);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (82, 'note', 11);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (83, 'note book', 11);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (84, 'class note', 11);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (85, 'course note', 11);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (86, 'finance', 12);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (87, 'Finance', 12);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (88, 'advanced', 12);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (89, 'course material', 12);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (90, 'text book', 12);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (91, 'material', 12);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (92, 'linear', 13);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (93, 'Linear', 13);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (94, 'algebra', 13);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (95, 'Algebra', 13);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (96, 'linear algebra', 13);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (97, 'material', 13);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (98, 'class material', 13);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (99, 'course material', 13);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (100, 'math', 13);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (101, 'music', 14);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (102, 'Music', 14);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (103, 'foundational', 14);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (104, 'foundation', 14);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (105, 'feedback', 14);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (106, 'course feedback', 14);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (107, 'finance', 15);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (108, 'Finance', 15);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (109, 'feedback', 15);
INSERT INTO `mydb`.`Keyword` (`keyword_id`, `word`, `post_id`) VALUES (110, 'course feedback', 15);

COMMIT;

