-- MySQL Script generated by MySQL Workbench
-- Wed Dec 20 22:59:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Post` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Post` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `post_title` VARCHAR(100) NOT NULL,
  `post_type` ENUM('course_note', 'course_material', 'course_feedback') NOT NULL,
  `post_description` VARCHAR(1000) CHARACTER SET 'armscii8' NULL,
  `member_id` INT NOT NULL,
  PRIMARY KEY (`post_id`),
  UNIQUE INDEX `post_id_UNIQUE` (`post_id` ASC) VISIBLE,
  CONSTRAINT `post_connect_member`
    FOREIGN KEY (`member_id`)
    REFERENCES `mydb`.`Member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Post`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Post` (`post_id`, `post_title`, `post_type`, `post_description`, `member_id`) VALUES (1, 'system analysis note book', 'course_note', 'This is my note please check', 1);
INSERT INTO `mydb`.`Post` (`post_id`, `post_title`, `post_type`, `post_description`, `member_id`) VALUES (2, 'algorithm note', 'course_note', 'note of algorithm.It take me lot of time to do it.', 1);
INSERT INTO `mydb`.`Post` (`post_id`, `post_title`, `post_type`, `post_description`, `member_id`) VALUES (3, 'finance material', 'course_material', 'this material is the course material of IM074', 1);
INSERT INTO `mydb`.`Post` (`post_id`, `post_title`, `post_type`, `post_description`, `member_id`) VALUES (4, 'english course feedback', 'course_feedback', 'great course! The teacher is keed and willing to teach student in patient. We watch movie in class. Not only learn lots of English vocabularies but also enjoy a great movie.', 1);
INSERT INTO `mydb`.`Post` (`post_id`, `post_title`, `post_type`, `post_description`, `member_id`) VALUES (5, 'chinese  course feedback', 'course_feedback', 'bad ass! terrible! DO NOT CHOOSE THIS COURSE', 1);
INSERT INTO `mydb`.`Post` (`post_id`, `post_title`, `post_type`, `post_description`, `member_id`) VALUES (6, 'intermediate math', 'course_note', 'this is my note, please take a look', 2);
INSERT INTO `mydb`.`Post` (`post_id`, `post_title`, `post_type`, `post_description`, `member_id`) VALUES (7, 'accounting course note', 'course_note', 'I love this class. enjoy you accounting journey.', 2);
INSERT INTO `mydb`.`Post` (`post_id`, `post_title`, `post_type`, `post_description`, `member_id`) VALUES (8, 'linear algebra', 'course_material', 'this is very hard! Take care.', 2);
INSERT INTO `mydb`.`Post` (`post_id`, `post_title`, `post_type`, `post_description`, `member_id`) VALUES (9, 'foundational phsics text book', 'course_material', 'you must get this book', 2);
INSERT INTO `mydb`.`Post` (`post_id`, `post_title`, `post_type`, `post_description`, `member_id`) VALUES (10, 'system analysis feedback', 'course_feedback', 'l love this class, but the final project\'s deadline is too early. holy shit! don\'t choose this course.You will regret! ', 2);
INSERT INTO `mydb`.`Post` (`post_id`, `post_title`, `post_type`, `post_description`, `member_id`) VALUES (11, 'chemistry class note', 'course_note', 'i\'m freshman in NCU. I found this note on internet and I want to share it to you', 3);
INSERT INTO `mydb`.`Post` (`post_id`, `post_title`, `post_type`, `post_description`, `member_id`) VALUES (12, 'advanced finance', 'course_material', 'this is my text book', 3);
INSERT INTO `mydb`.`Post` (`post_id`, `post_title`, `post_type`, `post_description`, `member_id`) VALUES (13, 'linear algebra material', 'course_material', 'give you guys the material we use in class IM2099', 3);
INSERT INTO `mydb`.`Post` (`post_id`, `post_title`, `post_type`, `post_description`, `member_id`) VALUES (14, 'music foundational course', 'course_feedback', 'I really enjoy this class. The teacher can sing well. Just like a singer. I recommend every come to our class.', 3);
INSERT INTO `mydb`.`Post` (`post_id`, `post_title`, `post_type`, `post_description`, `member_id`) VALUES (15, 'finance feedback', 'course_feedback', 'i love finance. I know that I will be investment master in the future.', 3);

COMMIT;

